### ISSUE TITLE
Allow dark theming color for default background

### ISSUE THREAD

**Issue by Lumrenion** [nextcloud/nextcloud-vue-dashboard#160]
My nextcloud installation has a rather light background image. When I select "Default images" in the dashboard, the greeting text as well as header icons turn white and are not readable. Same goes for "plain color".
<img width="495" alt="Bildschirmfoto 2021-03-01 um 09 58 25" src="https://user-images.githubusercontent.com/9381204/109474353-b6680f00-7a74-11eb-99d4-22ef5b5fcad0.png">

I cannot find any way to set the color of header icons in configuration. This should be added

**Comment by raimund-schluessler** [comment]
This is nothing we can solve here and needs to handled in the server repository, see https://github.com/nextcloud/server/issues/25952. This repository here is only for the components shown inside the widgets, not the whole dashboard itself.
