### ISSUE TITLE
@nextcloud/vue-dashboard@1.1.0 requires a peer of @nextcloud/vue@^2.3.0

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/nextcloud-vue-dashboard#188]
```
npm WARN @nextcloud/vue-dashboard@1.1.0 requires a peer of @nextcloud/vue@^2.3.0 but none is installed. 
You must install peer dependencies yourself.
```

**Comment by juliushaertl** [comment]
Whereever that occured, why not use https://github.com/nextcloud/nextcloud-vue-dashboard/releases/tag/v2.0.0 then ? :wink:

**Comment by skjnldsv** [comment]
Server lol 
https://github.com/nextcloud/server/blob/403388269a15c11e06c8d8585fefec4e78aa343b/package.json#L43

**Comment by juliushaertl** [comment]
Hm but why is dependabot the not suggesting a bump?

**Comment by juliushaertl** [comment]
Strangely https://www.npmjs.com/package/@nextcloud/vue-dashboard doesn't list 2.0.0 as the latest version, any idea why that might be the case @skjnldsv ?

**Comment by skjnldsv** [comment]
You have pushed 1.1.0 after 2.0.0

**Comment by juliushaertl** [comment]
Pushed a 2.0.1 and dependabot seems to pick that up now: https://github.com/nextcloud/deck/pull/3074
