### ISSUE TITLE
Split widget `item` prop

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue-dashboard#19]
How about splitting https://github.com/nextcloud/nextcloud-vue-dashboard/blob/4c900f4bd84e98f5659daf23f81440d1cb77f4db/src/DashboardWidgetItem.vue#L210-L213 into multiple props so you have IDE completion and proper validation on the things that are expected vs the things that are optional?

**Comment by eneiluj** [comment]
Very true thanks!
