### ISSUE TITLE
Onlyoffice Dashboard issues 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/nextcloud-vue-dashboard#195]
Linking this ticket https://github.com/nextcloud/server/issues/24889 i wasnt sure if this would be an issue on the dashboard so i just wanted to see what the recommendation is regarding this issue.

**Comment by juliushaertl** [comment]
This repo is only for shared user interface components for building dashboard widgets, for ONLYOFFICE related issues please open a ticket at https://github.com/ONLYOFFICE/onlyoffice-nextcloud/
