### ISSUE TITLE
There are no text strings in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/nextcloud-vue-dashboard#236]
I noticed that there are no text strings to translate in Transifex. Currently, there is a mix of translations in NC, for example:
Two text strings concatenated:
https://github.com/nextcloud/nextcloud-vue-dashboard/blob/master/src/DashboardWidget.vue#L75
https://github.com/nextcloud/tasks/blob/bb3e91810d242bab90fa98775de696f87c7d8755/src/views/Dashboard.vue#L30

Concatenated text string: `More upcoming tasks …`
He gives us a sentence not fully translated which looks strange: `More nadchodzących zadań …`

The topic discussed in PR: https://github.com/nextcloud/tasks/pull/1650

@juliushaertl @eneiluj Please add text strings to Transifex 😁. It certainly requires it #2.

**Comment by raimund-schluessler** [comment]
Fixed now that the dashboard components were merged into nextcloud-vue, see https://github.com/nextcloud/nextcloud-vue/pull/2668
