### ISSUE TITLE
Bug in version publish action

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/nextcloud-vue-dashboard#3]
The action publishing a new version to npm registry is failing:
```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/@nextcloud%2fvue-dashboard - Not found
npm ERR! 404 
npm ERR! 404  '@nextcloud/vue-dashboard@0.1.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

I guess it might be caused by an incorrect npm_token.

**Comment by juliushaertl** [comment]
@jancborchardt Could you make me admin of the repo so that i can store a secret for npm there?

**Comment by jancborchardt** [comment]
@juliushaertl @eneiluj done! :)

**Comment by eneiluj** [comment]
It's still not working. Don't know why.

**Comment by juliushaertl** [comment]
Turns out the secret needs to be NPM_TOKEN :see_no_evil: Tested and works now https://github.com/nextcloud/nextcloud-vue-dashboard/runs/1004996684?
