### ISSUE TITLE
Is this now the main Dashboard repo?

### ISSUE THREAD

**Issue by sunjam** [nextcloud/nextcloud-vue-dashboard#38]
Clarifying as I see the app store listing still points to the old Dashboard repo with no updates for years.

https://apps.nextcloud.com/apps/dashboard
https://github.com/nextcloud/dashboard
https://github.com/nextcloud/dashboard/issues/64

**Comment by juliushaertl** [comment]
No the dashboard app is part of the server repo https://github.com/nextcloud/server/

This repo is a vue js library for providing UI utilities to app developers who integrate with the new dashboard. 

cc @jancborchardt I guess we should archive the old dashboard repo to make it a bit more clear that it is obsolete.

**Comment by jancborchardt** [comment]
Done, thanks @juliushaertl for the pull request and reminder. :)
