### ISSUE TITLE
Allow empty content slot to render with optional additional list items

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-vue-dashboard#4]
The current approach in talk is quite hacky, ideally we allow to show both at the same time if needed:

![image](https://user-images.githubusercontent.com/3404133/90405195-bf2e6000-e0a3-11ea-967f-0f57533a3123.png)

cc @jancborchardt @eneiluj @nickvergessen

**Comment by eneiluj** [comment]
@juliushaertl It would be nice indeed. Now the question is how :grin:. Should we choose a fixed size for the empty content and set the item number to a fixed value too? How about 50-50, it would mean 50% height for empty content and 3 (or 4) items.
