### ISSUE TITLE
Merge components into @nextcloud/vue

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue-dashboard#407]
I would like to propose to merge the two Dashboard components into `nextcloud/vue` (sorry if this has been discussed already).

The short reason for this is that the effort of maintaining a separate repository for only two components is not worth the rather ideological benefit of doing so.

The longer list of reasons for merging is:
- The `nextcloud-vue-dashboard` repository is quite outdated (showing that the effort is quite high):
  - It still uses `nextcloud/vue@3`. This would be immediately tackled if the Dashboard components would live in `nextcloud/vue` itself.
  - The whole rollup config is old and `rollup-plugin-vue` is not even maintained anymore (they recommend using `vite` and `@vitejs/plugin-vue` now).
- To my knowledge, this repo is the only one using `rollup` yet. While `rollup` seems nice, this more than doubles the effort to maintain `nextcloud/vue` and `nextcloud/vue-dashboard` separately.
- The repository has basically no dependencies besides `nextcloud/vue`. Merging it into `nextcloud/vue` would not increase the package size of either package.
- All of the above makes the migration towards vue 3 more cumbersome as if it would live in `nextcloud/vue`. While the components themself don't need any change for vue 3 (just a small one for nextcloud/vue@5), the configuration is a bit challenging (for me, I couldn't get it to work properly with vue 3 yet, see my try in #406).

The only rational against merging I could think of is that the two components are not used *within* an app, hence, don't strictly belong to components logically. But in my opinion this is more than outweighed by the above reasons.

@eneiluj @juliushaertl @nickvergessen @marcoambrosini @skjnldsv Since you contributed the most here.

In case you are ok with this approach, I am happy to send a PR with the necessary adjustments to `nextcloud/vue`. (In fact, I have the two components in my `nextcloud/vue#vue3` https://github.com/nextcloud/nextcloud-vue/pull/2637 branch already, since I couldn't get it to work as a standalone repo yet, npm link is a challenge here as well).

**Comment by nickvergessen** [comment]
I think this is more due to historic reasons and in the beginning we thought it might be better to have a set of small things that do exactly 1 thing and not 1 giant lib to do everything, but I'm only a consumer of the repo. I have 0 clue about packaging/rollup and other strategies

**Comment by juliushaertl** [comment]
Yes, I'd agree that it probably makes more sense to move those components into the library these days.

> The only rational against merging I could think of is that the two components are not used within an app, hence, don't strictly belong to components logically. But in my opinion this is more than outweighed by the above reasons.

Would still be fine I'd say as `@nextcloud/vue` also allows individual imports of components so the app bundling can take care of only embedding the required parts.

**Comment by nickvergessen** [comment]
Same for https://github.com/nextcloud/nextcloud-vue-collections I guess?

**Comment by raimund-schluessler** [comment]
> Same for https://github.com/nextcloud/nextcloud-vue-collections I guess?

There I am not sure. `nextcloud-vue-collections` requires `vuex` and brings an own store, which `nextcloud/vue` does not. This _could_ create issues. Nonetheless it's just as outdated, with the last relase 1.5 years ago 😄🙈

**Comment by raimund-schluessler** [comment]
The PR to merge the Dashboard components is in https://github.com/nextcloud/nextcloud-vue/pull/2668.

**Comment by raimund-schluessler** [comment]
Done.

**Comment by nickvergessen** [comment]
So we archive this after adding a last message to the readme?

**Comment by raimund-schluessler** [comment]
> So we archive this after adding a last message to the readme?

I would say so, see https://github.com/nextcloud/nextcloud-vue-dashboard/issues/419

**Comment by korelstar** [comment]
But I think there is no release of nc-vue with this change yet.

**Comment by nickvergessen** [comment]
Doesn't matter? We will not remove existing packages from npm, so you can continue using those.
Archiving just means no one can create new issues/prs and also dependabot doesn't try to update things
