### ISSUE TITLE
Add hint for the move to nextcloud-vue, and archive repository

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue-dashboard#419]
Once we have a new release of nextcloud-vue including https://github.com/nextcloud/nextcloud-vue/pull/2668, we should add a note that the components were moved, and then archive this repository here.

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/nextcloud-vue-dashboard/commit/0916a24f20273d151d3e0ea0603ca57951169caf
